---
title: "Week8_Maps-3"
author: "Patrick Torralba"
format: html
editor: visual
---


```{r library + load}
library(janitor) # we can use this to clean column names!
library(sf)
library(tidyverse)
us_counties.df <- st_read("USA_Counties/USA_Counties.shp") %>% janitor::clean_names()
```

```{r}
head(us_counties.df)

```

```{r}
us_counties.sfc <- st_geometry(us_counties.df)

us_counties.sfc
```

```{r}
single.sfg <- us_counties.sfc[[1]]

single.sfg[[1]][[1]][1:10,]
```

# Plotting Minnesota Counties by Population in 2010 Census

```{r}
library(tidyverse)
us_counties.df %>%
  filter(state_name %in% "Minnesota") %>%
  ggplot() +
  geom_sf(aes(fill = log(pop2010))) +
  labs(
    title = "2010 US Census Population Estimates for MN Counties"
  ) +
  scale_fill_viridis_c("2010 Population (log)", option = "C") +
  theme(legend.position = "right")
```

```{r}
library(plotly)
minn_pop.plot <- us_counties.df %>%
  filter(state_name %in% "Minnesota") %>%
  mutate(
    text_label = str_c(name, "\nPopulation: ", round(pop2010 / 1000, 0), " K") # making label for hover
  ) %>%
  ggplot() +
  geom_sf(aes(fill = log(pop2010), text = text_label),
          colour = "black", size = 0.8, alpha = 0.6) + # thickens and darkens border
  labs(
    title = "2010 US Census Population Estimates for MN Counties"
  ) +
  scale_fill_viridis_c("2010 Population (log)", option = "C") +
  theme_void() # removes axes and labels

# Use plotly to add hover!

ggplotly(minn_pop.plot, tooltip = 'text') %>% style(hoveron = 'fills')
```

```{r}
library(tidycensus)

options(tigris_use_cache = TRUE) 

mn_income.df <- get_acs(
  geography = "tract",
  variables = "B19013_001", #Code for median income
  state     = "MN",
  county    = "Hennepin",
  year      = 2020,
  geometry  = TRUE,
  cb        = FALSE
)

head(mn_income.df)
```

```{r}

mn_income_plotly.df <- mn_income.df %>%
  mutate(
    tract      = str_split(NAME, ",") %>%
                 map_chr(1) %>%
                 str_remove("Census Tract "),
    text_label = str_c(
                  "Tract: ",
                  tract,
                  "\nMedian Income: ",
                  scales::dollar(estimate)
                 )
  )

# Building plot
income.gg <- ggplot() + 
  geom_sf(data = mn_income_plotly.df, aes(fill = estimate, text = text_label)) + 
  labs(title = "Hennepin County 2020 ACS Estimated Median Income") + 
  theme_void() + 
  scale_fill_viridis_c("Median Income", option = "C", labels = scales::dollar)

income.gg
```

```{r}
ggplotly(income.gg,
         tooltip = "text",
         height  = 600,
         width   = 800) %>%
    style(hoveron = "fills")
```

```{r}
library(osmdata)

minny_bb <- getbb("Minneapolis") 

minny_bb
```

```{r}
minny_shop_sf.df <- minny_bb %>% opq %>% 
             add_osm_feature(key = "shop", value = c("alcohol", "supermarket", "books", "tattoo")) %>%
  osmdata_sf()

#Extract the relevent sf data frame
shop_points.df <- minny_shop_sf.df$osm_points %>% 
  janitor::clean_names() %>%
  filter(!is.na(shop)) %>% #only retain 'valid' tags
  dplyr::select(osm_id, name, shop, opening_hours, phone, website, geometry) %>%
  mutate(shop = str_to_title(shop) %>% as_factor())

head(shop_points.df)
```

```{r}
library(ggmap)
register_stadiamaps(key = "fc6bfacf-f6bb-4d75-a921-e283b14b7b56", write=TRUE) 
```

```{r}
library(ggmap)

minn_base.map <- get_map(location = minny_bb, source = "stadia", maptype = "stamen_toner_lite")

minn_base.gg <- ggmap(minn_base.map) + theme_void()

minn_base.gg
```

```{r}
minn_base.gg +
  geom_sf(data = shop_points.df,
          aes(colour = shop),
          inherit.aes = FALSE,
          alpha = 0.8, shape = 16) +
  labs(title = "Minneapolis, MN OSM Features") + 
  scale_colour_viridis_d("Store", option = "C") +
  theme(
    plot.title   = element_text(size  = 16,
                                hjust = 0.5),
    legend.text  = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.position = "right"
  )
```

```{r}
library(leaflet)

#Call viridis library  
library(viridis, quietly = TRUE)

#Extract the levels/order of shop type factor
shop_types <- levels(shop_points.df$shop)
n_types    <- length(shop_types)

#Initialize our colour pallete (discrete in this case)
my_pallete <- colorFactor(viridis_pal(option = "C")(n_types), levels = shop_types)

#Call our leaflet
leaflet(data = shop_points.df) %>%
  addProviderTiles('CartoDB.Positron') %>% 
  addCircleMarkers(
    color   = ~my_pallete(shop),
    opacity = 0.4,
    weight  = 2, #outline strength
    radius  = 4 #size of circle
  ) %>%
  addLegend(
    title    = "Store Type",
    position = "bottomright",
    colors   = viridis_pal(option = "C")(n_types),
    labels   = shop_types 
  )
```

```{r}
library(htmltools, quietly = TRUE)

#Add a text label like normal
shop_label.df <- shop_points.df %>%
  mutate(
    across(
      c(name, opening_hours:website),
      ~ifelse(is.na(.x), "NA", .x)
    ),
    text_label = str_c(
                   name,
                   "<br/>Store Type: ",
                   shop,
                   "<br/>Open Hours: ",
                   opening_hours,
                   "<br/>Phone: ",
                   phone,
                   "<br/>Website: ",
                   website
                 )
  )


#Redisplay the leaflet
shop_label.df %>%
  leaflet() %>%
  addProviderTiles('CartoDB.Positron') %>% 
  addCircleMarkers(
    color   = ~my_pallete(shop),
    label   = ~purrr::map(text_label, HTML), #map over labels, make html
    opacity = 0.6, #alpha
    weight  = 4, #outline strength
    radius  = 4 #size of circle
  ) %>%
  addLegend(
    title    = "Store Type",
    position = "bottomright",
    colors   = viridis_pal(option = "C")(n_types),
    labels   = shop_types 
  )
```

