---
title: "Assignment 5"
author: "Patrick Torralba"
format: html
editor: visual
---

```{r}
#| label: library
#| echo: false
#| warning: false
#| message: false

library(tidyverse)
library(sf)
library(plotly)
library(tidycensus)
library(osmdata)
library(ggmap)
library(leaflet)
library(viridis, quietly = TRUE)

```

```{r}
#| label: load counties
#| echo: false
#| warning: false
#| message: false

us_counties.df <- st_read("USA_Counties/USA_Counties.shp") %>% janitor::clean_names()

```

# Task 1: USA Counties Data

## Plotting Kansas Counties by Age Under 5 Population

```{r}
#| label: fig-ks-counties-under5
#| fig-cap: "Age Under 5 Population Estimate for KS Counties"

ks_u5_pop.plot <- us_counties.df %>% 
  filter(state_name == "Kansas") %>% 
  mutate(
    text_label = str_c(name , "\nPopulation: ", round(age_under5 / 1000,0),"K") # hover label
        ) %>%
  ggplot() +
  geom_sf(aes(fill = log(age_under5),
              text = text_label)) +
  labs(title = "Age Under 5 Population Estimate for KS Counties") +
  scale_fill_viridis_c("Age Under 5 (log)", option = "C") +
  theme(legend.position = "right") +
  theme_void()

ggplotly(ks_u5_pop.plot, tooltip = 'text') %>% 
  style(hoveron = 'fills')

```

## Plotting Kansas Counties by Asian Population

```{r}
#| label: fig-ks-counties-Asian
#| fig-cap: "Asian Population Estimate for Ks Counties"
#| fig-cap-location: "top"


ks_asian_pop.plot <- us_counties.df %>% 
  filter(state_name == "Kansas") %>% 
  mutate(
    text_label = str_c(name , "\nPopulation: ", round(asian / 1000,0),"K") # hover label
        ) %>%
  ggplot() +
  geom_sf(aes(fill = log(asian),
              text = text_label)) +
  labs(title = "Asian Population Estimate for KS Counties") +
  scale_fill_viridis_b("Asian (log)", option = "D") +
  theme(legend.position = "right") +
  theme_void()

ggplotly(ks_asian_pop.plot, tooltip = 'text') %>% 
  style(hoveron = 'fills')

```


# Task 2: Census Data

## New York Census Map

```{r}
#| label: NY-males-df-clean


NY_males.df <- get_acs(
  geography = "tract",
  variables = "B01001_002", # code for males
  state = "NY",
  county = "Kings",
  year = 2023,
  geometry = TRUE,
  cb = FALSE
)

options(tigris_use_cache = TRUE)

head(NY_males.df)

```

```{r}
#| label: NY-males-df-ploty

NY_males_plotly.df <- NY_males.df %>% 
  mutate(
    tract = str_split(NAME, ",") %>% 
            map_chr(1) %>% 
            str_remove("Census Tract "),
    text_label = str_c(
                        tract,
                        "<br>",
                        "\nMale Population: ",
                        format(estimate, big.mark = ",")
    ))


```



```{r}
#| label: fig-NY-counties-male-pop
#| fig-cap: "New York counties male pop"
#| fig-cap-location: "top"

male.gg <- ggplot() +
  geom_sf(data = NY_males_plotly.df, aes(fill = estimate, text = text_label)) +
  labs(title = "King County 2023 ACS Estimated Male Population") +
  theme_void() +
  scale_fill_viridis_c("Male Population", option = "C")


male.gg
```

```{r}
#| label: fig-male-pop-hover-plotly
#| fig-cap: "King County Male Population"
#| fig-cap-location: "top"

ggplotly(male.gg,
         tooltip = "text",
         height = 600,
         width = 800) %>% 
  style(hoveron = "fills")



```


# Task 3: OpenStreetMap and Leaflet
```{r}
#| label: st-paul

st_paul <- getbb("St.Paul")

st_paul

```

```{r}
#| label: st-paul-restaurant

st_paul_restaurant_sf.df <- st_paul %>% 
  opq %>% 
  add_osm_feature(key = "amenity",
                  value = "restaurant") %>% 
  osmdata_sf()

#Extract sf data frame

restaurants.df <- st_paul_restaurant_sf.df$osm_points %>% 
  janitor::clean_names() %>% 
  filter(!is.na(amenity)) %>% 
  dplyr::select(amenity, osm_id, name, shop, opening_hours, phone, website, geometry, `addr_city`, `addr_housenumber`, `addr_street`) %>% 
  mutate(amenity = str_to_title(amenity) %>% as_factor())
  
head(restaurants.df)


```


```{r}
#| label: stadiamaps-api

register_stadiamaps(key = "fc6bfacf-f6bb-4d75-a921-e283b14b7b56", write=TRUE) 
```

```{r}
#| label: fig-st-paul-gg
#| fig-cap: "St paul ggmap"
#| fig-cap-location: "top"


st_paul_base.map <- get_map(location = st_paul, source = "stadia", maptype = "stamen_toner_lite")

st_paul_base.gg <- ggmap(st_paul_base.map) + theme_void()

st_paul_base.gg

```


```{r}
#| label: fig-stpaul-restaurants-wip
#| fig-cap: "St Paul Restaurants"
#| fig-cap-location: "top"


st_paul_base.gg +
  geom_sf(data = restaurants.df,
          aes(color = shop),
          inherit.aes = FALSE) +
  labs(title = "St. Paul, MN Restaurants") +
  scale_color_viridis_d("Restaurant Type", option = "C")

```


```{r}
#| label: fig-leaflet
#| fig-cap: "St Paul Restaurant Leaflet"
#| fig-cap-location: "top"

pal <- colorFactor(palette = "viridis", domain = restaurants.df$shop)

leaflet(data = st_paul_restaurant_sf.df$osm_points) %>% 
  addProviderTiles('CartoDB.Positron') %>% 
  addCircleMarkers(
    color = ~pal(shop),
    weight = 2,
    radius = 4,
    label = ~name
  ) %>% 
  addLegend(
    pal = pal,
    values = ~shop,
    title = "Restaurant Type",
    position = "bottomright")
```

